name: vehicle_manager
description: "A Flutter project for vehicle management" 
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.8 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  characters: ^1.4.0
  material_color_utilities: ^0.11.1
  meta: ^1.17.0
  sqflite: ^2.4.2
  path: ^1.9.1
  image_picker: ^1.2.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  lints: ^6.1.0
  matcher: ^0.12.17
  test_api: ^0.7.7

flutter:
  uses-material-design: true
  assets:
    - .env